version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'secret'
      MYSQL_DATABASE: 'polygon'
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "33066:3306"
volumes:
  mysql_data: {}